### ISSUE TITLE
use IntersectionSet class in diffHic

### ISSUE THREAD

**Issue by hurleyLi** [LTLA/diffHic#5]
Hi Aaron, 

Thanks for this nice package! 
I'm also trying to feed the diffHic package with contact matrix called from another pipeline, and I saw this issue #4 that mentioned using InteractionSet package with the iset branch of diffHic. But I have real hard time installing the R-devel version and these packages on the cluster, since I don't have root permissions and I had to specify dependencies etc, and I'm really not a masochists. So just wondering do you have a timeline of publishing the InteractionSet and iset diffHic through bioconductor? 

If not, maybe I can try to use the current version of diffHic from the raw data. I did tried to begin from the raw using ```presplit_map.py```, but I don't quite understand what do you mean by ```synchronize mate pair``` in ```Users are strongly recommended to synchronize mate pair information```. Could you please be more specific of how to process after the presplit_map. 

Thanks!
Hurley

**Comment by LTLA** [comment]
The _InteractionSet_ package has been submitted to Bioconductor, and the technical review is well underway (second round of revisions have been submitted). Once that is accepted, _diffHic_ will switch over to using the _InteractionSet_ classes. Note, however, that you'll still have to use R-devel to get access to BioC-devel packages. If you can't do that, you'll have to wait until mid-April once the new BioC release comes out. It's simply too much effort to reconfigure the two packages to work on the current BioC release.

The alignment information as it comes out of `presplit_map.py` does not have sensible entries in the mate fields of the output BAM fields. It's generally useful to run, e.g., `FixMateInformation` from the _Picard_ suite to set these fields sensibly. Further details can be found in the epilogue of the user's guide, which gives you a link to a shell script containing all the necessary commands to align a Hi-C library.

**Comment by hurleyLi** [comment]
Hi Aaron, 

I finally managed to transferred all data on my one machine, install R-3.3 and plan to try diffHic islet on my locally. I came across this error when I try to install the diffHic islet branch
I'm using this devtools command:
```install_github("LTLA/diffHic/package@iset")```
The error I got
```
** testing if installed package can be loaded
Warning: replacing previous import ‘S4Vectors::rowMeans’ by ‘Matrix::rowMeans’ when loading ‘diffHic’
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/diffHic/libs/diffHic.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/diffHic/libs/diffHic.so, 6): Library not loaded: /Users/biocbuild/bbs-3.3-bioc/meat/Rhtslib.buildbin-libdir/Rhtslib/lib/libhts.0.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/diffHic/libs/diffHic.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/diffHic’
Error: Command failed (1)
```
It looks like the diffHic.so is missing from the package?

Buy the way, I just finished a ChiPseq differential binding analysis using csaw, and it worked great! Keep all the good work rolling!! 

Thanks,
Hurley

**Comment by LTLA** [comment]
Seems like you need to check your installation of _Rhtslib_.

**Comment by hurleyLi** [comment]
Yes, when I update my _Rhtslib_ to version 1.3.2, it works!! I'll try it out based on the instructions on #4 , and I'm sure I'll bother you again for questions. Thanks a lot!
