### ISSUE TITLE
Error when call preparePairs

### ISSUE THREAD

**Issue by hurleyLi** [LTLA/diffHic#6]
Hi Aaron, 
I came across an error when I run the development version of diffHic (iset branch)
```
diagnostics <- preparePairs("SRR027957.qSorted.bam", hs.param,file="SRR027957.h5", dedup=TRUE, minq=10)
Error in preparePairs("SRR027957.qSorted.bam", hs.param, file = "SRR027957.h5",  : 
  failed to open output file at './file3ef645949ed1/19_16'
```
it always complains about the output file with random names
The same command run well on diffHic 1.2.2

**Comment by LTLA** [comment]
Well, the random file is a temporary folder in which `preparePairs` stores intermediate files prior to constructing the hdf5 file. In your case,  it looks like the file opening is failing in the compiled code at the `fopen` call. There's not much that can go wrong from the coding point of view, so I can only conclude that it's something to do with your system. Here's a couple of things to check:

- make sure you're not deleting the temporary folder in the middle of `preparePairs`'s run.
- make sure you have write access to the current directory. This should be okay if release works.
- see whether example(preparePairs) runs, to determine if it's a specific problem with your BAM file.

If all those things are good, see if you can whittle the file down to a minimum working example that can reproduce the error, I'll see what I can do.

**Comment by LTLA** [comment]
If you're using Windows, it seems that `dir.create` has some eccentricities that might cause some problems. Try commenting out the `on.exit` line in `preparePairs.R`, and make sure that the `file_*` directory is actually being constructed (and is writable).

**Comment by flay** [comment]
Hi Aaron, 

I am also having issue when trying to run preparePairs for bam files that I have aligned through hicup and HiC-Pro. These bam files are then name sorted using samtools. 

```
 diagnostics=preparePairs("test_sort.bam", hs.param, file="test.h5", dedup=TRUE, minq=10)
Error in chromosomes[[chrs[x]]] : subscript out of bounds
```
hs.param is defined exactly as shown in the user's guide. Running `example(preparePairs)` worked, so it may be my BAM files, but I am not sure what specifically. 

I would appreciate it if you have suggestions. Thank you!

**Comment by LTLA** [comment]
If you're using release _diffHic_, this question would be best posted to the Bioconductor support site.
