### ISSUE TITLE
presplit_map.py 

### ISSUE THREAD

**Issue by will-NYGC** [LTLA/diffHic#7]
I'm trying to use presplit_map.py on the command line to process my FASTQs but I get this error:
```
Traceback (most recent call last):
  File "presplit_map.py", line 101, in <module>
    oline=original.next().strip()
StopIteration
```

**Comment by LTLA** [comment]
This error would only occur if your original FASTQ file has fewer entries than in the `splitted_temp.fq` produced by `cutadapt`. This should not be possible, as `cutadapt` will return all entries (even zero-length ones after trimming) by default. Check `splitted_temp.fq` and make sure there's the same number of lines as in your original FASTQ files. Note that multi-line read sequences are not supported by `presplit_map.py`.

**Comment by will-NYGC** [comment]
i’ve checked the number of lines and it is the same in splitted_temp.fq and original file. Is there a specific cutadapt version I should be using? I have cutadapt v1.9.1 installed.


On Apr 5, 2016, at 6:37 PM, Aaron Lun <notifications@github.com<mailto:notifications@github.com>> wrote:


This error would only occur if your original FASTQ file has fewer entries than in the splitted_temp.fq produced by cutadapt. This should not be possible, as cutadapt will return all entries (even zero-length ones after trimming) by default. Check splitted_temp.fq and make sure there's the same number of lines as in your original FASTQ files. Note that multi-line read sequences are not supported by presplit_map.py.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/LTLA/diffHic/issues/7#issuecomment-206017188>

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by LTLA** [comment]
Hm... I'm stumped. Try running `presplit_map.py` with `python -i`, and - when it breaks - print out what the value of `line` is. And see where that value shows up in the original file and in `splitted_temp.fq`.

**Comment by LTLA** [comment]
More generally, what happens when you open up Python and run:

```
original=open(curf, "rU") # replace 'curf' with your original fastq file name.
for line in open("splitted_temp.fq", "rU"):
    line=line.strip()
    oline=original.next().strip()
```

If this throws an error, then there must be a different number of lines in the file.

**Comment by will-NYGC** [comment]
ah… gzipped fastq needed to be decompressed. thanks for help.


On Apr 5, 2016, at 7:26 PM, Aaron Lun <notifications@github.com<mailto:notifications@github.com>> wrote:


More generally, what happens when you open up Python and run:

original=open(curf, "rU") # replace 'curf' with your original fastq file name.
for line in open("splitted_temp.fq", "rU"):
    line=line.strip()
    oline=original.next().strip()


If this throws an error, then there must be a different number of lines in the file.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/LTLA/diffHic/issues/7#issuecomment-206032243>

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.
