### ISSUE TITLE
ICE offset

### ISSUE THREAD

**Issue by will-NYGC** [LTLA/diffHic#8]
Hi Aaron,

I'm trying to include offsets for NB loess, CNV, and ICE correction by doing something like this:

```
y <- asDGEList(data)
y$offset <- nb.offset + cnv.offset + ice.offset
```

But, I get this error:
```
Error in y[, j] <- fitted(locfit::locfit(y[, j] ~ x, weights = weights,  :
  number of items to replace is not a multiple of replacement length
```

These offsets are all 2163068 x 4 matrices, 1 column for each sample, 2 conditions, 2 reps. Is it possible to account for all these offsets in the DGEList object?

**Comment by LTLA** [comment]
Several points:

- Unless you're using the experimental version, this is a question that should go on the BioC support site.
- You're going to have to be more specific about what code you've used to trigger the error.
- For DI analyses, we don't think it's necessary to do ICE correction. It adds a lot of complexity and uncertainty for not much gain.
